Add repository and deploy docs
Open-Telecoms-Data/standard-development-handbook pull request #25
Opened 2023-01-10 22:55 UTC by duncandewhurst

2023-01-12 13:43 UTC, lgs85 requested changes
Looks good, just a couple of bits added.

2023-01-12 13:43 UTC, lgs85 commented on docs/technical/deploy.md
> +
```suggestion

### Update readthedocs

You can skip this step if you are not releasing a new major or minor version.

When releasinog a new major or minor version, the new release should be set to the 'latest' version, and all previous versions should be visible in the flyout menu on readthedocs. To do this:

- Log in to readthedocs and open the `open-fibre-data-standard` project. You will need ODSC admin credentials to do this.
- To set the new release to be the 'latest' branch, to 'Admin' ? 'Advanced settings and change the option.
- To change the visibility of the new and previous versions in the flyout, go to 'Versions' and 'Edit' on relevant versions. The 'Hidden' checkbox will determine if a version is visible in the flyout menu.
```

2023-01-12 21:45 UTC, duncandewhurst commented
Thanks! I made a few more updates:

* Add an instruction to update `reference/publication_formats/json.md` (looks like we missed that in the 0.2.0 release)
* Add a section explaining how Read the Docs is configured and separate explanatory content from the process docs
* Move the instructions for updating Read the Docs to the end of the end, since we don't want to make new versions live until CoVE is updated
* Copy-edit instructions for updating Read the Docs

2023-01-13 13:04 UTC, lgs85 approved these changes

2023-01-13 13:04 UTC, merged